apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: nodejs-app 
  namespace: nodejs 
  labels:
    app: nodejs-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 345999536858.dkr.ecr.us-east-1.amazonaws.com/nodejs:latest
          ports:
            - containerPort: 8000
          env: 
            - name: DB_USER
              value: "postgres"
            - name: DB_DATABASE
              value: "postgres_db"
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "postgres-service" 
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef: 
                  name: db-password-secret 
                  key: DB_PASSWORD
---
apiVersion: v1 
kind: Service 
metadata:
  name: nodejs-app-service 
  namespace: nodejs 
spec:
  selector:
    app: nodejs-app 
  type: LoadBalancer
  ports:
    - name: nodejs-app
      port: 8000
      targetPort: 8000 
