apiVersion: apps/v1
kind: Deployment  
metadata:
  name: postgres
  namespace: nodejs 
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec: 
      containers:
        - name: postgres
          image: postgres:13 
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres" 
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB 
              value: "postgres_db"
            - name: PGDATA
              value:  /var/lib/postgresql/data/pgdata 
          volumeMounts:
            - name: postgres-storage 
              mountPath: /var/lib/postgresql/data
      volumes:   
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-app-pvc 
---
apiVersion: v1 
kind: Service 
metadata:
  name: postgres-service
  namespace: nodejs 
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432 
--- 
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: postgres-app-pvc 
  namespace: nodejs 
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 3Gi
