apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: nodejs-app 
  namespace: nodejs
  labels:
    app: nodejs-app 
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: mostafaabdelkhalek8/nodejs
          ports:
            - containerPort: 8000
          env: 
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "postgres-service" 
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret 
                  key: DB_PASSWORD
            - name: DB_DATABASE
              value: "postgres_db"
            - name: DB_PORT 
              value: "5432"
---
apiVersion: v1 
kind: Service 
metadata: 
  name: nodejs-app-svc 
  namespace: nodejs
spec: 
  type: NodePort 
  selector:
    app: nodejs-app
  ports:
    - name: nodejs-app-svc 
      port: 8000
      targetPort: 8000 
